version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: ../backend/
    container_name: foodgram_backend
    env_file:
      - .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../data/:/data/
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    build: ../frontend
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
    command: cp -r /app/build/. /static/

  gateway:
    container_name: foodgram_gateway
    image: nginx:1.22.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - backend
      - frontend
